on: push
name: Build, Audit and Publish
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: ci
    - name: Audit dependencies
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: audit
    - name: Tag
      uses: actions/bin/filter@9d4ef995a71b0771f438dd7438851858f4a55d0c
      with:
        args: tag
    - name: Publish to npm
      uses: actions/npm@3c8332795d5443adc712d30fa147db61fd520b5a
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
    - name: Create Github Release
      uses: felixbrucker/github-actions/publish-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --name Foxy-Miner
    - name: Post to Discord
      uses: felixbrucker/github-actions/post-release-in-discord@master
      env:
        FOXY_DISCORD_WEBHOOK_ID: ${{ secrets.FOXY_DISCORD_WEBHOOK_ID }}
        FOXY_DISCORD_WEBHOOK_TOKEN: ${{ secrets.FOXY_DISCORD_WEBHOOK_TOKEN }}
